id: P6522A3C3
initial_creation_type: ocr
source_metadata:
  volumes:
    09a71df6cdbe48ca9a847292462b777d:
      base_file: v039.txt
      image_group_id: I1PD95884
      title: སྒྲོལ་མའི་སྒྲུབ་ཐབས།
      total_pages: 1625
      volume_number: 39
